# Generated by Django 5.2.4 on 2025-11-24 08:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='FontAwesome icon class (e.g., fa-wifi)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('property_type', models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('guesthouse', 'Guest House'), ('homestay', 'Homestay')], default='hotel', max_length=20)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('distance_from_temple', models.CharField(help_text='e.g., 200m from Dwarkadhish Temple', max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per night', max_digits=10)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Average rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('star_rating', models.IntegerField(default=3, help_text='Star category (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('has_temple_view', models.BooleanField(default=False)),
                ('has_free_cancellation', models.BooleanField(default=True)),
                ('has_breakfast', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section on homepage')),
                ('badge', models.CharField(blank=True, help_text='e.g., Best Rated, Top Pick, Premium, New', max_length=50)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='hotels/main/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='hotels.amenity')),
            ],
            options={
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(help_text='Rating 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('stay_date', models.DateField(help_text='When did the guest stay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Approve review to show on website')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Deluxe Room, Suite, Standard Room', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_guests', models.IntegerField(default=2)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.IntegerField(default=1, help_text='Total rooms available')),
                ('is_available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel')),
            ],
            options={
                'ordering': ['price_per_night'],
            },
        ),
    ]
