# Generated by Django 4.2.7 on 2025-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('room', 'Room'), ('food', 'Food & Dining'), ('facility', 'Facility')], default='room', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Dwarka', max_length=120),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional latitude for map integrations', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional longitude for map integrations', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='hotels.amenity'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('suite', 'Suite')], default='double', max_length=20),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveIntegerField(default=2, help_text='Total guests allowed'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/rooms/'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='size_sqft',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(help_text='Icon class (Bootstrap Icons, e.g., bi-wifi)', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='hotels/main/'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.FileField(upload_to='hotels/gallery/'),
        ),
    ]
