# Generated by Django 4.2.7 on 2025-12-01 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0002_amenity_category_hotel_city_hotel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who left the review (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
