# Generated by Django 4.2.7 on 2025-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location_zone',
            field=models.CharField(choices=[('dwarkadhish', 'Dwarkadhish Temple'), ('gomti_ghat', 'Gomti Ghat'), ('dwarka_beach', 'Dwarka Beach'), ('bet_dwarka', 'Bet Dwarka'), ('other', 'Dwarka City (Other)')], default='dwarkadhish', help_text='Primary Dwarka landmark this hotel is closest to', max_length=40),
        ),
    ]
