# Generated by Django 5.2.4 on 2025-11-24 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code (e.g., FIRST500, TEMPLE20)', max_length=50, unique=True)),
                ('description', models.CharField(help_text='User-friendly description', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 20) or Fixed amount (e.g., 500)', max_digits=10)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum booking amount to apply coupon', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage type)', max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('max_uses', models.IntegerField(default=100, help_text='Maximum number of times this coupon can be used')),
                ('used_count', models.IntegerField(default=0, help_text='Number of times already used')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, help_text='Auto-generated unique booking ID', max_length=20, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.IntegerField(help_text='Number of nights')),
                ('num_adults', models.IntegerField(default=2)),
                ('num_children', models.IntegerField(default=0)),
                ('num_rooms', models.IntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Room price x nights x rooms', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Hotel discount amount', max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, help_text='GST and other taxes', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final amount to be paid', max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requirements from guest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype')),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for guest bookings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.')], max_length=5)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('license', 'Driving License'), ('passport', 'Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_detail', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Guest Detail',
                'verbose_name_plural': 'Guest Details',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('payathotel', 'Pay at Hotel')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_successful', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Any payment-related notes')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
