# Generated by Django 4.2.7 on 2025-12-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, default='', help_text='Razorpay order identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, default='', help_text='Razorpay payment identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_signature',
            field=models.CharField(blank=True, default='', help_text='Signature returned by Razorpay', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('razorpay', 'Pay Online (Razorpay)'), ('payathotel', 'Pay at Hotel')], max_length=20),
        ),
    ]
